### ISSUE TITLE
Chiral center in VS095 3D structure isn't tetrahedral

### ISSUE THREAD

**Issue by ricrogz** [CIPValidationSuite/ValidationSuite#3]
I have noticed that the 3D structure for VS095 represents a tetragonal pyramid rather than a tetrahedral chiral center. 

Looking at the 2D representation, I would expect the phenyl and hydroxyphenyl groups to point in different directions in respect to the other ring, but in the 3D representation they both point in the same direction.

**Comment by johnmay** [comment]
The 2D is the primary data, 3D coords were generated with Jmol (@BobHanson). If you can provide an updated 3D structure I am happy to make the patch.

**Comment by ricrogz** [comment]
Attaching an updated structure: [VS095_3d_new.sdf.txt](https://github.com/CIPValidationSuite/ValidationSuite/files/3923803/VS095_3d_new.sdf.txt)

**Comment by johnmay** [comment]
Thanks

**Comment by ricrogz** [comment]
Thanks to you for the quick fix! :)
